### ISSUE TITLE
Request to Make Usable in a List/RecyclerView

### ISSUE THREAD

**Issue by EdwardQuixote** [ImangazalievM/CircleMenu#10]
I honestly loved this piece of work. It's amazing.

Unfortunately, I found it hard to use on a RecyclerView. Mainly because of the elevation of the Circle Button. So I'm requesting you to have it possible to use in a list item/RecyclerView item.
Maybe removing the background and elevation could be a starting point?

**Comment by ImangazalievM** [comment]
I have not idea why you want to use this library with RecyclerView. Could you give me an example?

**Comment by EdwardQuixote** [comment]
@ImangazalievM please check this [Invision Freehand](https://projects.invisionapp.com/freehand/document/4CBdZ4EhZ), to understand what I mean.
The CircleMenu could provide a menu for a RecyclerView item.
I hope I'm clearer now.

**Comment by ImangazalievM** [comment]
Sorry, but it's impossible.
