### ISSUE TITLE
default open a menu

### ISSUE THREAD

**Issue by naraharirajesh** [ImangazalievM/CircleMenu#12]
Hi, it looks awesome. But i dint find a tricky  to open menu directly, user wants to see the menu options directly, will you please help me in that..    
circleMenu.setStateUpdateListener() in that, onMenuExpanded is menu opening. i need to perform through pro-grammatically.

**Comment by ImangazalievM** [comment]
You can use ```openOnStart``` attribute (added in verstion 2.0.0):

<com.imangazaliev.circlemenu.CircleMenu
        ...
        app:openOnStart="true">
