### ISSUE TITLE
Start activity after completing effect

### ISSUE THREAD

**Issue by ziselos** [ImangazalievM/CircleMenu#13]
How can we start another activity or fragmet after circle fill effect completes on button clicked?
Now,  on button pressed starts another activity but the user can not see the circle fill effect completely because transition starts imediately. Can we set a delay or something like that?

**Comment by ImangazalievM** [comment]
Added EventListener in version 2.0.0:

```java
circleMenu.setEventListener(new CircleMenu.EventListener() {

            @Override
            public void onButtonClickAnimationEnd(@NonNull CircleMenuButton menuButton) {

            }

});
```

**Comment by ziselos** [comment]
Thanks, this was exactly what i wanted to do.
