### ISSUE TITLE
error on api 15

### ISSUE THREAD

**Issue by blennerSilva** [ImangazalievM/CircleMenu#14]
it says it supports min sdk 15 but im getting an error on that\

Error:Execution failed for task ':ubook:processUbookDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.github.imangazalievm:circlemenu:2.0.0] /Users/blennersilva/.gradle/caches/transforms-1/files-1.1/circlemenu-2.0.0.aar/7b81f5e57fedae5d6eae66f9e9b7f100/AndroidManifest.xml as the library might be using APIs not available in 15
  	Suggestion: use a compatible library with a minSdk of at most 15,
  		or increase this project's minSdk version to at least 16,
  		or use tools:overrideLibrary="com.imangazaliev.circlemenu" to force usage (may lead to runtime failures)

**Comment by ImangazalievM** [comment]
Fixed in version 2.0.1

**Comment by ImangazalievM** [comment]
Fixed in version 2.0.1

**Comment by blennerSilva** [comment]
not the issue related but is there anyway to put texts in the buttons ?

**Comment by ImangazalievM** [comment]
No. But you can enable hints, that shows in Toast by long pressing a button

```java
<com.imangazaliev.circlemenu.CircleMenu
        ...
        app:hintsEnabled="true">

        <com.imangazaliev.circlemenu.CircleMenuButton
                   ...
                   app:hintText="Place"/>

        ...

</com.imangazaliev.circlemenu.CircleMenu>
```

**Comment by blennerSilva** [comment]
thanks
