### ISSUE TITLE
On parent view position change animations no longer line up

### ISSUE THREAD

**Issue by NathanJamesWoolmore** [ImangazalievM/CircleMenu#22]
I have an ad banner that sits underneath the layout and when removed (Visiblility.GONE) the layout shifts down.
Once the layout moves down the menu moves too however the menu buttons still refer to the last position before the view had changed. Basically the animation now centers slightly above where it should.

Great library by the way, just can't seem to find a fix for this issue..

**Comment by ImangazalievM** [comment]
Can you create a sample project, that reproduces your problem, and publish it on GitHub?

**Comment by NateJamesW** [comment]
@ImangazalievM hey thanks for checking out the issue - yep I'll try make one at some point today or tomorrow and post the link here.

**Comment by NateJamesW** [comment]
The issue only seems to occur with fragments, I made a sample project in a similar way to the one that I'm experiencing the issue on, have a look here - https://github.com/NateJamesW/CircleMenuIssueExample/tree/master
