### ISSUE TITLE
java.lang.IllegalArgumentException: 

### ISSUE THREAD

**Issue by sutanurath** [ImangazalievM/CircleMenu#31]
java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).

 Binary XML file line #7: Error inflating class com.imangazaliev.circlemenu.CircleMenu

This error coming with .AppCompat Theme

Please help

**Comment by ImangazalievM** [comment]
@sutanurath I apologize for ignoring your issue. Couldn't find time to answer you. I suppose that it will resolve your problem: https://stackoverflow.com/questions/21814825/you-need-to-use-a-theme-appcompat-theme-or-descendant-with-this-activity

**Comment by sutanurath** [comment]
Hello @ImangazalievM
Thanks for looking into my issue. Its working on activity or fragment but its not working in service. I was trying to use in custom layout.
Please goto this link, I have rised a question on stackoverflow.
https://stackoverflow.com/questions/64263455/android-inflate-view-with-app-theme-from-service

**Comment by ImangazalievM** [comment]
I think that is not possible because to inflate **CircleMenu** you have to use themed context (i. e. `ContextThemeWrapper`), but it works with Activities only. I may be wrong, but this is what I have come to while researching this issue.
