### ISSUE TITLE
Open menu programmatically

### ISSUE THREAD

**Issue by gaborvecsei** [ImangazalievM/CircleMenu#5]
Hi!

It would be nice if we could open the menu programmatically, so we don't have to press the center button.

**Comment by ImangazalievM** [comment]
Added toggle method in version [1.0.3](https://github.com/ImangazalievM/CircleMenu/releases/tag/1.0.3)

**Comment by ImangazalievM** [comment]
Added toggle method in version [1.0.3](https://github.com/ImangazalievM/CircleMenu/releases/tag/1.0.3)
