### ISSUE TITLE
Graphic glitches while expanding menu first time after application launch

### ISSUE THREAD

**Issue by a13xsus** [ImangazalievM/CircleMenu#6]
Spotted some graphic glitch while expanding menu every single first time after application launch. Reveals on all supported api versions (below and above 19).

![qemu-system-i386-2017-05-08-16-14-58-54](https://cloud.githubusercontent.com/assets/26189467/25806929/a9ff2142-340d-11e7-9bd9-8cb051f7ffc7.gif)

All icons are popped up for a moment and then immediately have gone.

**Comment by arthurprogramming** [comment]
Same here.

**Comment by AladdinHZ** [comment]
any luck to solve it ?

**Comment by ImangazalievM** [comment]
A new version with fixes will be available in a few hours

**Comment by arthurprogramming** [comment]
Thank you so much, sir!

**Comment by ImangazalievM** [comment]
No problem)
