### ISSUE TITLE
icon with text

### ISSUE THREAD

**Issue by muhammedfayazp** [ImangazalievM/CircleMenu#7]
can we use center as oval button and text.. or the center button invisible and other visible..
and also need add text below the icon.. is there any solution?

**Comment by mhmdgoma** [comment]
I'm currently working on CircleMenuButton class to allow adding text below or above the icon ..  Once finish I will try to post my solution.

**Comment by ImangazalievM** [comment]
Unfortunately, it's impossible to implement in the design of CircleMenu (it will look ugly). But you can use hints for buttons (see Readme).

**Comment by muhammedfayazp** [comment]
ok no problem. i had done with my own code
